name: local_package_run_rector

# This test will run on every pull request, and on every commit on any branch
on:
        [push, pull_request]

jobs:
    run_rector_on_rector_examples_module:
        name: Run Drupal Rector
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"

#           Uncomment to enable SSH access to Github Actions - https://github.com/marketplace/actions/debugging-with-tmate#getting-started
#            - name: Debugging with tmate
#              uses: mxschmitt/action-tmate@v2
            -   run: |
                    # Download the composer plugin that downloads packages in parallel to speed up the installation process.
                    composer global require hirak/prestissimo
            -   run: |
                    # Download the latest Drupal core project and all its dependencies
                    composer create-project srijanone/ezcontent-project:8.x-dev ../drupal --no-interaction --no-progress
                    mv ../drupal/* ..