name: local_package_run_drupal

# This test will run on every pull request, and on every commit on any branch
on:
        [push, pull_request]

jobs:
    run_build_process:
        name: Run Drupal Ezcontent
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"
            -   uses: mirromutth/mysql-action@v1.1
                with:
                    host port: 3800 # Optional, default value is 3306. The port of host
                    container port: 3307 # Optional, default value is 3306. The port of container
                    character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
                    collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
                    mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
                    mysql database: 'testdb' # Optional, default value is "test". The specified database which will be create
                    mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
                    mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
                    mysql password: ${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"

#           Uncomment to enable SSH access to Github Actions - https://github.com/marketplace/actions/debugging-with-tmate#getting-started
#            - name: Debugging with tmate
#              uses: mxschmitt/action-tmate@v2
            -   run: |
                    # Download the composer plugin that downloads packages in parallel to speed up the installation process.
                    composer global require hirak/prestissimo
                    composer global require zaporylie/composer-drupal-optimizations:^1.1
            -   run: |
                    # Download the drush packages
                    composer global require drush/drush:8.*
            -   run: |
                    # Download the latest Drupal core project and all its dependencies
                    composer create-project srijanone/ezcontent-project:8.x-dev drupal --no-interaction --no-progress
            -   run: |
                    # Setting up the stage.
                    cd drupal
                    COMPOSER_MEMORY_LIMIT=-1 composer update
                    mkdir -p docroot/sites/default/files
                    chmod -R 777 docroot/sites/default/files
                    mkdir -p private-files
                    chmod -R 777 private-files
                    cp docroot/sites/default/default.settings.php docroot/sites/default/settings.php
                    chmod -R 777 docroot/sites/default/settings.php
                    echo "if (PHP_SAPI === 'cli') { ini_set('memory_limit', '512M');}" >> docroot/sites/default/settings.php